on:
  workflow_dispatch:
  schedule:
    - cron: '*/5 * * * *'

jobs:
  test_schedule:
    runs-on: ubuntu-latest
    steps:
      - name: Every 5 minutes cron
        run: echo "This step will always run in every 5 minutes"