name: every five minute cron job
on:
  schedule:
    - cron: '0/5 * * * *'
jobs:
  cron:
    runs-on: ubuntu-latest
    steps:
      - name: five minute cron job
        run: echo "Testing cron for 5 minutes"